name: tests
run-name: Testing commit from ${{ github.actor }}
on: [push, pull_request]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install nodejs and npm
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
      - name: Check out repository code
        uses: actions/checkout@v5
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test